2020-08-16 00:13:34,405 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 577151ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 01:05:11,534 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 3077113ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 04:11:56,964 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 11165619ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 07:05:25,641 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 10388667ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 10:18:42,265 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 11555836ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 19:26:20,687 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 27637593ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-16 22:25:12,952 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 10652113ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-17 08:58:03,148 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 33964362ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-17 13:16:04,342 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 15321161ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-17 13:24:09,190 ERROR 2272 nodejs.ClusterClientNoResponseError: client no response in 464832ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 2272
hostname: senge.local

2020-08-24 18:37:36,758 ERROR 26759 [-/127.0.0.1/-/37ms POST /api/v1/file] nodejs.ReferenceError: sendToWormhole is not defined
    at FileController.create (/Users/kuban/Desktop/InterviewQuestionManage/app/controller/file.js:25:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 26759
hostname: senge.local

2020-08-24 18:37:36,841 ERROR 26759 nodejs.ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265456753.jpg' (uncaughtException throw 1 times on pid:26759)
ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265456753.jpg' (uncaughtException throw 1 times on pid:26759)
errno: -2
code: "ENOENT"
syscall: "open"
path: "app/public/uploads/1598265456753.jpg"
name: "ENOENTError"
pid: 26759
hostname: senge.local

2020-08-24 18:38:57,031 ERROR 27670 [-/127.0.0.1/-/26ms POST /api/v1/file] nodejs.ReferenceError: sendToWormhole is not defined
    at FileController.create (/Users/kuban/Desktop/InterviewQuestionManage/app/controller/file.js:25:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 27670
hostname: senge.local

2020-08-24 18:38:57,093 ERROR 27670 nodejs.ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265537025.jpg' (uncaughtException throw 1 times on pid:27670)
ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265537025.jpg' (uncaughtException throw 1 times on pid:27670)
errno: -2
code: "ENOENT"
syscall: "open"
path: "app/public/uploads/1598265537025.jpg"
name: "ENOENTError"
pid: 27670
hostname: senge.local

2020-08-24 18:45:08,361 ERROR 27878 [-/127.0.0.1/-/10ms POST /api/v1/file] nodejs.ReferenceError: sendToWormhole is not defined
    at FileController.create (/Users/kuban/Desktop/InterviewQuestionManage/app/controller/file.js:25:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 27878
hostname: senge.local

2020-08-24 18:45:08,368 ERROR 27878 nodejs.ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265908360.jpg' (uncaughtException throw 1 times on pid:27878)
ENOENTError: ENOENT: no such file or directory, open 'app/public/uploads/1598265908360.jpg' (uncaughtException throw 1 times on pid:27878)
errno: -2
code: "ENOENT"
syscall: "open"
path: "app/public/uploads/1598265908360.jpg"
name: "ENOENTError"
pid: 27878
hostname: senge.local

2020-08-24 23:49:44,020 ERROR 27876 nodejs.ClusterClientNoResponseError: client no response in 16755158ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27876
hostname: senge.local

2020-08-25 09:35:33,240 ERROR 27876 nodejs.ClusterClientNoResponseError: client no response in 35009162ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27876
hostname: senge.local

